### ISSUE TITLE
Error when running ./bot.sh start

### ISSUE THREAD

**Issue by lifelongeek** [MIPTDeepLearningLab/ConvAI-baseline#3]
First of all, thanks for sharing your baseline with us.
Here is the error message when running ./bot.sh start.
Below is the procedure that I followed.

1) ./setup.sh
2) Make my telegram bot and replace token as my bot.
3) ./bot.sh start

There are few strange things 
 - bot.sh call python3.4 where I completely removed from my system. Currently, I only have python2.7 & python3.6
 - bot.py does not recognize my bot's token 

I really appreciate any information.

Traceback (most recent call last):
  File "bot_code/bot.py", line 11, in <module>
    from telegram import ChatAction
ModuleNotFoundError: No module named 'telegram'
Creating stub config...
You need to replace STUB with your actual token in file config.ini
Traceback (most recent call last):
  File "bot_code/bot.py", line 156, in <module>
    ai = Bot()
  File "bot_code/bot.py", line 60, in __init__
    self.updater = Updater(TOKEN)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 77, in __init__
    self.bot = Bot(token, base_url)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 51, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 75, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
Traceback (most recent call last):
  File "bot_code/bot.py", line 156, in <module>
    ai = Bot()
  File "bot_code/bot.py", line 60, in __init__
    self.updater = Updater(TOKEN)
  File "/usr/local/lib/python3.4/dist-packages/telegram/ext/updater.py", line 77, in __init__
    self.bot = Bot(token, base_url)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 51, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.4/dist-packages/telegram/bot.py", line 75, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
Traceback (most recent call last):
  File "bot_code/bot.py", line 10, in <module>
    import configparser
ImportError: No module named configparser
Traceback (most recent call last):
  File "bot_code/bot.py", line 11, in <module>
    from telegram import ChatAction
ModuleNotFoundError: No module named 'telegram'
Traceback (most recent call last):
  File "bot_code/bot.py", line 11, in <module>
    from telegram import ChatAction
ImportError: cannot import name 'ChatAction'
Traceback (most recent call last):
  File "bot_code/bot.py", line 11, in <module>
    from telegram import ChatAction
ImportError: cannot import name 'ChatAction'
Python 3.6.0 :: Anaconda custom (64-bit)

**Comment by madrugado** [comment]
Hi Geonmin,

First of all, you shouldn't share the secret of your bot here, please remove it.
Secondly, we are using python 3, not exactly 3.4. It seems to me that, your symlink for python3 is pointing to purged python3.4. May be you could reinstall anaconda.

Best Regards,
Valentin

**Comment by lifelongeek** [comment]
Thanks for the reply.
I will follow your instruction.
